import type { Metadata } from "next";
import { Noto_Sans_SC, JetBrains_Mono } from "next/font/google";
import "./styles/globals.css";
import ReduxProvider from "@/components/ReduxProvider";
import Header from "@/components/layout/Header";
import Sidebar from "@/components/layout/Sidebar";

const notoSansSC = Noto_Sans_SC({
  weight: ['400', '500', '700', '900'],
  subsets: ["latin"],
  variable: "--font-sans",
});

const jetBrainsMono = JetBrains_Mono({
  weight: ['400', '500', '700'],
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en" data-theme="gold">
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />
      </head>
      <body
        className={`${notoSansSC.variable} ${jetBrainsMono.variable} antialiased flex flex-col h-screen overflow-hidden`}
      >
        <ReduxProvider>
          <Header />
          <div className="flex flex-1 overflow-hidden">
            <Sidebar />
            <main className="flex-1 overflow-y-auto bg-[var(--bg-deep)]">
              {children}
            </main>
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
};

export default RootLayout;
